name: fhglassets
description: A sample command-line application.
version: 0.0.4
homepage: https://github.com/hackerhgl/fhglassets
repository: https://github.com/hackerhgl/fhglassets
issue_tracker: https://github.com/hackerhgl/fhglassets/issues

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  recase: ^4.0.0

executables:
  fhglassets:
